# profile config
# 参考地址: https://www.baeldung.com/spring-profiles
spring:
  profiles:
    active: dev

# mybatis config
mybatis:
  config-location: classpath:sqlMapConfig.xml

# logging config
logging:
  level:
    tech.qijin.mall-server.db: DEBUG

